const ResumeApi = [
    {
      id: 1,
      category: "education",
      year: "Generation Australia",
      title: "Junior Web Developer Bootcamp",
      desc: "",
      rate: "",
    },
    {
      id: 2,
      category: "education",
      year: "",
      title: "",
      desc: "",
      rate: "",
    },
    {
      id: 3,
      category: "education",
      year: "Shahab-Danesh University",
      title: "Bachelor of Science in Electronics Engineering",
      desc: "",
      rate: "",
    },
    {
    id: 4,
    category: "education",
    year: "",
    title: "",
    desc: "",
    rate: "",
    },
    {
      id: 5,
      category: "experience",
      year: "June 2020 - present",
      title: "Frntend Developer",
      desc: "",
      rate: "",
    },
    {
      id: 6,
      category: "experience",
      year: "June 2018 - February 2020",
      title: "Frontend Developer",
      desc: "",
      rate: "",
    },
    {
      id: 7,
      category: "experience",
      year: "",
      title: "",
      desc: "",
      rate: "",
    },
    {
      id: 8,
      category: "experience",
      year: "",
      title: "",
      desc: "",
      rate: "",
    },
];
  
export default ResumeApi;